### ISSUE TITLE
[v8] DGII Ventas

### ISSUE THREAD

**Issue by edser-pcg** [MarcosCommunity/odoo#11]
El módulo marcos_ncf está tomando los datos del Diario de compras + Diario de ventas para generar el 607. Puedes confirmar?

El log no muestra ningún error al ejecutar la generación del 607 e inclusive se ve que esta generando el reporte dgii.sale.report

**Comment by eneldoserrata** [comment]
Gracias por reportarlo, Revisa el codigo en la linea donde se filtran las facturas que se van a procesar, no debe ser dificil de corregir.
